/**********************************************************************
 *
 * Copyright (C) Imagination Technologies Ltd. All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope it will be useful but, except 
 * as otherwise stated in writing, without any warranty; without even the 
 * implied warranty of merchantability or fitness for a particular purpose. 
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
 * 
 * The full GNU General Public License is included in this distribution in
 * the file called "COPYING".
 *
 * Contact Information:
 * Imagination Technologies Ltd. <gpl-support@imgtec.com>
 * Home Park Estate, Kings Langley, Herts, WD4 8LZ, UK 
 *
 ******************************************************************************/

#ifndef _SGX543DEFS_KM_H_
#define _SGX543DEFS_KM_H_

#define EUR_CR_BREAKPOINT_TRAP              0x0F78
#define EUR_CR_BREAKPOINT_TRAP_CONTINUE_MASK 0x00000002U
#define EUR_CR_BREAKPOINT_TRAP_CONTINUE_SHIFT 1
#define EUR_CR_BREAKPOINT_TRAP_CONTINUE_SIGNED 0
#define EUR_CR_BREAKPOINT_TRAP_WRNOTIFY_MASK 0x00000001U
#define EUR_CR_BREAKPOINT_TRAP_WRNOTIFY_SHIFT 0
#define EUR_CR_BREAKPOINT_TRAP_WRNOTIFY_SIGNED 0
#define EUR_CR_BREAKPOINT                   0x0F7C
#define EUR_CR_BREAKPOINT_MODULE_ID_MASK    0x000003C0U
#define EUR_CR_BREAKPOINT_MODULE_ID_SHIFT   6
#define EUR_CR_BREAKPOINT_MODULE_ID_SIGNED  0
#define EUR_CR_BREAKPOINT_ID_MASK           0x00000030U
#define EUR_CR_BREAKPOINT_ID_SHIFT          4
#define EUR_CR_BREAKPOINT_ID_SIGNED         0
#define EUR_CR_BREAKPOINT_UNTRAPPED_MASK    0x00000008U
#define EUR_CR_BREAKPOINT_UNTRAPPED_SHIFT   3
#define EUR_CR_BREAKPOINT_UNTRAPPED_SIGNED  0
#define EUR_CR_BREAKPOINT_TRAPPED_MASK      0x00000004U
#define EUR_CR_BREAKPOINT_TRAPPED_SHIFT     2
#define EUR_CR_BREAKPOINT_TRAPPED_SIGNED    0
#define EUR_CR_BREAKPOINT_TRAP_INFO0        0x0F80
#define EUR_CR_BREAKPOINT_TRAP_INFO0_ADDRESS_MASK 0xFFFFFFF0U
#define EUR_CR_BREAKPOINT_TRAP_INFO0_ADDRESS_SHIFT 4
#define EUR_CR_BREAKPOINT_TRAP_INFO0_ADDRESS_SIGNED 0
#define EUR_CR_BREAKPOINT_TRAP_INFO1        0x0F84
#define EUR_CR_BREAKPOINT_TRAP_INFO1_SIZE_MASK 0x00007C00U
#define EUR_CR_BREAKPOINT_TRAP_INFO1_SIZE_SHIFT 10
#define EUR_CR_BREAKPOINT_TRAP_INFO1_SIZE_SIGNED 0
#define EUR_CR_BREAKPOINT_TRAP_INFO1_NUMBER_MASK 0x00000300U
#define EUR_CR_BREAKPOINT_TRAP_INFO1_NUMBER_SHIFT 8
#define EUR_CR_BREAKPOINT_TRAP_INFO1_NUMBER_SIGNED 0
#define EUR_CR_BREAKPOINT_TRAP_INFO1_TAG_MASK 0x000000F8U
#define EUR_CR_BREAKPOINT_TRAP_INFO1_TAG_SHIFT 3
#define EUR_CR_BREAKPOINT_TRAP_INFO1_TAG_SIGNED 0
#define EUR_CR_BREAKPOINT_TRAP_INFO1_DATA_MASTER_MASK 0x00000006U
#define EUR_CR_BREAKPOINT_TRAP_INFO1_DATA_MASTER_SHIFT 1
#define EUR_CR_BREAKPOINT_TRAP_INFO1_DATA_MASTER_SIGNED 0
#define EUR_CR_BREAKPOINT_TRAP_INFO1_RNW_MASK 0x00000001U
#define EUR_CR_BREAKPOINT_TRAP_INFO1_RNW_SHIFT 0
#define EUR_CR_BREAKPOINT_TRAP_INFO1_RNW_SIGNED 0
#define EUR_CR_USE_CODE_BASE_0              0x0A0C
#define EUR_CR_USE_CODE_BASE_ADDR_00_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_00_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_00_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_00_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_00_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_00_SIGNED   0
#define EUR_CR_USE_CODE_BASE_1              0x0A10
#define EUR_CR_USE_CODE_BASE_ADDR_01_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_01_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_01_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_01_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_01_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_01_SIGNED   0
#define EUR_CR_USE_CODE_BASE_2              0x0A14
#define EUR_CR_USE_CODE_BASE_ADDR_02_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_02_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_02_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_02_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_02_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_02_SIGNED   0
#define EUR_CR_USE_CODE_BASE_3              0x0A18
#define EUR_CR_USE_CODE_BASE_ADDR_03_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_03_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_03_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_03_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_03_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_03_SIGNED   0
#define EUR_CR_USE_CODE_BASE_4              0x0A1C
#define EUR_CR_USE_CODE_BASE_ADDR_04_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_04_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_04_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_04_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_04_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_04_SIGNED   0
#define EUR_CR_USE_CODE_BASE_5              0x0A20
#define EUR_CR_USE_CODE_BASE_ADDR_05_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_05_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_05_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_05_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_05_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_05_SIGNED   0
#define EUR_CR_USE_CODE_BASE_6              0x0A24
#define EUR_CR_USE_CODE_BASE_ADDR_06_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_06_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_06_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_06_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_06_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_06_SIGNED   0
#define EUR_CR_USE_CODE_BASE_7              0x0A28
#define EUR_CR_USE_CODE_BASE_ADDR_07_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_07_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_07_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_07_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_07_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_07_SIGNED   0
#define EUR_CR_USE_CODE_BASE_8              0x0A2C
#define EUR_CR_USE_CODE_BASE_ADDR_08_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_08_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_08_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_08_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_08_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_08_SIGNED   0
#define EUR_CR_USE_CODE_BASE_9              0x0A30
#define EUR_CR_USE_CODE_BASE_ADDR_09_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_09_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_09_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_09_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_09_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_09_SIGNED   0
#define EUR_CR_USE_CODE_BASE_10             0x0A34
#define EUR_CR_USE_CODE_BASE_ADDR_10_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_10_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_10_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_10_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_10_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_10_SIGNED   0
#define EUR_CR_USE_CODE_BASE_11             0x0A38
#define EUR_CR_USE_CODE_BASE_ADDR_11_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_11_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_11_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_11_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_11_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_11_SIGNED   0
#define EUR_CR_USE_CODE_BASE_12             0x0A3C
#define EUR_CR_USE_CODE_BASE_ADDR_12_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_12_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_12_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_12_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_12_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_12_SIGNED   0
#define EUR_CR_USE_CODE_BASE_13             0x0A40
#define EUR_CR_USE_CODE_BASE_ADDR_13_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_13_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_13_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_13_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_13_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_13_SIGNED   0
#define EUR_CR_USE_CODE_BASE_14             0x0A44
#define EUR_CR_USE_CODE_BASE_ADDR_14_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_14_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_14_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_14_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_14_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_14_SIGNED   0
#define EUR_CR_USE_CODE_BASE_15             0x0A48
#define EUR_CR_USE_CODE_BASE_ADDR_15_MASK   0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_15_SHIFT  0
#define EUR_CR_USE_CODE_BASE_ADDR_15_SIGNED 0
#define EUR_CR_USE_CODE_BASE_DM_15_MASK     0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_15_SHIFT    26
#define EUR_CR_USE_CODE_BASE_DM_15_SIGNED   0
#define EUR_CR_USE_CODE_BASE(X)     (0x0A0C + (4 * (X)))
#define EUR_CR_USE_CODE_BASE_ADDR_MASK      0x03FFFFFFU
#define EUR_CR_USE_CODE_BASE_ADDR_SHIFT     0
#define EUR_CR_USE_CODE_BASE_ADDR_SIGNED    0
#define EUR_CR_USE_CODE_BASE_DM_MASK        0x0C000000U
#define EUR_CR_USE_CODE_BASE_DM_SHIFT       26
#define EUR_CR_USE_CODE_BASE_DM_SIGNED      0
#define EUR_CR_USE_CODE_BASE_SIZE_UINT32 16
#define EUR_CR_USE_CODE_BASE_NUM_ENTRIES 16

#endif 

